version: '3'

networks:
  default:
    driver: bridge

services:
  php:
    build:
      context: ./
    volumes:
      - ./source:/var/www:cached
    working_dir: /var/www
    tty: true
    networks:
      - default